apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cdcjLy8ovByfpQtC,iv:G0ysXjSgVwlLmjtc4LHu6fKTEWIik0VKhksowYvScNM=,tag:1pJ8csd/J8O9VF5cRV7aXQ==,type:str]
  BLOCKY_POSTGRES_PASS: ENC[AES256_GCM,data:FufvUEZm3042ddh/VxYnURTsZYw5fVeAB8uARarNmoQVtvRnSR0bt36S88LvmdIM0Q==,iv:Pcb28R99GM4hiS0LdiDvV4PSHbrn3739TyYe0cw+wPg=,tag:e7KVlwaZ7SnaU+8Bt7OyTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdmtmSTJkQUtuazgzM1pH
        TXFCRXRCU2thSFdsRG1ZbzJ2KzVUK3czY2h3Ck9WYUlhdzZhakRoczFaaWtNQzlU
        ZTZtTnFoandGQWl5WDF6WTVlc20xdWsKLS0tIFk4YUlTSGIwc2tHcjU3eVJoQkVH
        VDFvL2RhK1RnZVRSekdCcDJld0hJT1kKzVb8l7vSWThqdDEa4WCK6D/VirjgjDlx
        qeqd/tv+L2wdQU+3ypwd9Wkwmi7PRNutOmhf6avKFKVQYvadXxeULg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T14:20:07Z"
  mac: ENC[AES256_GCM,data:HXzPfFWGXJQzq+xMWtgtApTlc4CaclGSu3DAHQHMH2JA6yXdidxl7p75HWnoDMyj5YSRmegFqCcgzMtGYlvF+BhAB8nER3yYfcfUVIVzxdKlD+mOT85XBZUkf7CirKzPEQt2UqTxO2knRz4oueIMqu700wz18yBK6XfenoZGk8s=,iv:q8HGiCRRyVrZTtkFBjkwU8ZiA7lqhrSznzsfv5kElP4=,tag:Iuu0CZJW4Du203CWDUWL3Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
