---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  quote: '"' # double quote var to support substitution as quote
  # Cluster IP's (Cilium range [10.0.2.0/23])
  CLUSTER_K8S_GATEWAY_IP: 192.168.0.20
  CLUSTER_INTERNAL_ROUTE_IP: 192.168.0.21
  CLUSTER_EXTERNAL_ROUTE_IP: 192.168.0.22
  CLUSTER_BLOCKY_IP: 192.168.0.23
  CLUSTER_MOSQUITTO_IP: 192.168.0.24
  CLUSTER_HOME_ASSISTANT_IP: 192.168.0.25
  CLUSTER_CLOUDNATIVE_PG_17_IP: 192.168.0.26
  VECTOR_LOAD_BALANCER_IP: 192.168.0.27
  # External Services
  LAN_VOLUMIO: 192.168.5.3
  LAN_NETKEEPER_IP: 192.168.5.1
  LAN_PRINTER_IP: 192.168.5.4
  LAN_ZIGBEE_ADAPTER_IP: 10.0.2.123
  # Redis DB id's
  REDIS_BLOCKY_DB: "1"
  # Service URLs
  POSTGRES_HOST: "production-rw.database.svc.cluster.local"
  POSTGRES_PORT: "5432"

