apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:E2e5DOcSWwWbufpk/7yitKGf7ZpQlNloTZvP8WX9QqFpuUsZ0penr2Gb4rZZiibEVSuHb+WGfLpI3eSL1NWwFtrFzFfQZwd7+w7pFS+i/glm/+W1CVNDTihavsXKl7aplo5dtNn/yT2PUeSL/tGYy+aScVKPG+WRzQ==,iv:MUsjHZzMOiufnlU1ayqfOzK3PQcWQ87rnJW8QYGBLeE=,tag:/dvcPF2PpO44KJQI+36hsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcXQ4MlFoVUN4YklVZWZk
        eFlaNC8wSlhFb29mZG0wQ2p5aEE3WVU3QzNNClJhTyswYUJXWitNN2g5bmllbkVp
        RklrLzF4RGUzc2EwaTh4ekVSQms1UEUKLS0tIFZUTnZVdDJDNVBrYnBnbUs2bDht
        ZHhWbFZjd25jaWdaNEFkUGJVM1IyZ2cKZs7WNxmhEun1tDbt1linqHzvm0R2360y
        YQ38j+toAT9PbMkVXwGjlFr+4tmQ9WpoQzKlvEQBuhV9rQjagUmEgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T14:27:01Z"
  mac: ENC[AES256_GCM,data:ujShjvP689i0y2WsJCjQRs29kb9JHtKWZ4t66EP7N6bNDvLdZhbwcfgVmuUplUnw/8rQCnBRyZjd2SKnj9SKI9wiWdS/zIZf8T5w+E+kVN8AG7hFC87xEtrEfNODiu1HGegRXae9eznXBmskGU58buZiLwWAHuPnI9ZFkohspYY=,iv:7TjiWUVoGe6spMMeOddnrSnmDHI3+fX8ZSkWgE0wWUY=,tag:ywfj72VyxcNyb63u6Ige3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
