# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fiT/sGubEUpHsqtkmrfbtBKH7qqYlcE0vQwUplAHg91kpnKHrIPV5G9J7uKAfgAN7aR6Kws=,iv:rQTyzT6Fq6/NFSzkl/gw75GRFdx5p1Tt1pu8LM8y9WE=,tag:uL55f23UzJiEpkw3+iDx6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQjBtSUtENTkrVDZkTXpY
        Zk8vdlpCaFVBZ2VVcVBaVEV1L1M1eGgrVEJBCkZDK0QzNDFaa2R4VU15WWdKTGgz
        NEpCSkV3aEhrRWhTM0V1bGJtbTM5eVEKLS0tIDYwb0ZHNFJOYVR6QloxMUdTU0k1
        VEhXSmIvZ2NzclM2cDVFaHhxMldTcncKKHiHrQW/n3jlgT1SEGn3tbJCze92I8lY
        CsHsJMOq6o5MN8CrOoFmlQXl38Z9Ct1F3xlOMogWxaBscsQVdVmzHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T19:28:58Z"
  mac: ENC[AES256_GCM,data:xspHfgFjdKOAS3TPSY6TKqYxsOXXhKIunY9rzM+q/szaFEOvWpJHR2TDkWgQV5D2xqILxAWGmZdlv8SVmbiC0BRgfuIPZEbrtGMBlppClLZUYIV2+khpuDdfI6rOkkyGFjTWLmp8Qdp6VG67jxEaj9F41PkOqlwYghRFyIacdZM=,iv:NZbNbgseLPafsz0/esho/tfyw6ROVcOqtmnZXDtwXbs=,tag:AefsSQCAtKRG+6J/LTCBdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
