# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6EF2Hv/fCtx8IYmaxgOG6oGzesn7IIC3qccZunpsFU5VU2/p00JSSlRMMbnPyaI6FMMJkp0=,iv:xAAJVyHXS0okzQWFVqv9VtC5w47oko55zHhqDbCTd58=,tag:qjsIoyTiQJvp8MgdBaZj7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYWxGaklHQ241TkFWbHlK
        QkhQWFhySHR5c2tGOC9zbWorMEI5ZDMrR2hNCjl0MnBCS0FoVnBnN3d2MldNVFNn
        c2oxY1prYmU2QU0vR1FPZ1ExZHdYRm8KLS0tIGdDZG41WWdRWE42U0o5ODlDSElY
        Y29UeVRVMlJtRlBSWndCVEFvYWZHZ2cKlABGAbSBY3e808TdXEZBEtJUNtjg4QhA
        gYtIexdNOsqqSsTAHYzDExIZ2bDRVgWWc8D78jQapj0jdyJ4TEdcQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T19:29:02Z"
  mac: ENC[AES256_GCM,data:0Ldwr62W2Q+UxjJ0Hw0BjPAnGlIIDMlXxKcWoH2GzcHw43ulQq+wiihp2NKqxsYIIC9Ubl+oeymLz+8KPTNV9n2GPR32FCoPtYB6OK+eAOakq55RVqCnfYHcZPyj87VFz9EDHANWh3w1cUc13u2DFe6jCIX52Q80VaHFifNWm/A=,iv:DXUlDjyp11q10xMpL+wohFnZ/V8HBu8EB9P8b7vw05Q=,tag:FbE58b6GL7HkfoTRI9MpcQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
