# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lg/ctFY5q/wxPsbf41qb+Vv3vIm9y5oUNM42KpuzLc8J3sd1oDV6pR7ZTRc=,iv:tHY5wHiv21R1cjDW7MFY5mnhCpcstY1SGUjxJtXQwqo=,tag:aTdZh67i3/evYtIBS8GWpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYWxGaklHQ241TkFWbHlK
        QkhQWFhySHR5c2tGOC9zbWorMEI5ZDMrR2hNCjl0MnBCS0FoVnBnN3d2MldNVFNn
        c2oxY1prYmU2QU0vR1FPZ1ExZHdYRm8KLS0tIGdDZG41WWdRWE42U0o5ODlDSElY
        Y29UeVRVMlJtRlBSWndCVEFvYWZHZ2cKlABGAbSBY3e808TdXEZBEtJUNtjg4QhA
        gYtIexdNOsqqSsTAHYzDExIZ2bDRVgWWc8D78jQapj0jdyJ4TEdcQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T18:22:24Z"
  mac: ENC[AES256_GCM,data:RKLkhprb/d1yrjOT89Ut5/L2NKB1YtR1PbMHioZWRnqhB6xHf8wuWwz3zMjcBAJSVEZhblGzH+IfnqB69rbinSShLiMZHQetARnohvNQA0JAIe7mctItpZNnFAgodj5DLvcnfztpu1HT3DtJXzW2oIU7ZDalAtGBBxra/89hfBY=,iv:fJ1TG4/6dXKVytd4/Gv0U05f5bDl1Opt7+2b3WyZiM8=,tag:zSIzYhlr2nkdQViugKR3Tg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
