# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xLGCDfAMue6Avo1q9MeHq67YE1ZDnbng0jVquOcaLA1cHqlegsSYSsxjltO/BDFf8pz2KUI=,iv:HsrwmpQ5LgxoWEuZVcc/KeEQIoZf3aIBReU1mCVizpU=,tag:ddpcnYF3uIsH/2BMb44pVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0FCWExoMFpNRW1pTTJQ
        MnIrMFlqczllWW5JZHg4R1Z6Y0s4eE8xeGhZCjhlY3FQV25MSFNYa1hMemtHUm4y
        Q1NXNW9HeHNMOVdTQlQ2U29DNEJzYk0KLS0tIEtBWFNldnVsTmVjMENDdVdSdmQw
        TllDWUw1bFNSclkwVHVxdzEwUWMvUDgKjYemfEbUCA3W8MgkQc7QK4e08v9HBCTq
        SaFakgs/knUt41mQn8mjYL1my7QMUVPddujefsARz+qiiQyB2fQHGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T14:23:38Z"
  mac: ENC[AES256_GCM,data:p66nlIkUX9zJzhUA3RGiFrlBjVUcSXsVb5SX9JzCbVPz95pcVrqciQZHUpMAHJ+s/q7e1RgVvF7i5wdHEcrpOIOi4vft91Ba0m/OM8h9cvkTUAlijZ6XXXAM7IHlFQwd/jo0pRqMnwbfN9C/FtwNZPpROMt1qAvDAahXeTojSjw=,iv:vBjFiouborDnPplcMukWNa139YhQXid26nofh2GjJPk=,tag:xkzEhxp03frAruhUp/iHcw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
