# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: heneops

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.11:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.11"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "hene-10"
    ipAddress: "192.168.0.10"
    installDisk: # Intentionally left null to force selector use
    installDiskSelector:
      wwid: "eui.0000000001000000e4d25c5ae7ab5001"
    controlPlane: true
    machineSpec:
      secureboot: true
      arch: "amd64"
      mode: "metal"
    kernelModules:
      - name: vfio_pci
      - name: uio_pci_generic
      - name: nvme_tcp
      - name: ublk_drv
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - cpufreq.default_governor=performance # Default is powersave
          - iommu.passthrough=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/nfsd
            - siderolabs/nfsrahead
            - siderolabs/util-linux-tools
            - siderolabs/nvme-cli
            - siderolabs/iscsi-tools
            - siderolabs/fuse3
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.wwid == "eui.0000000001000000e4d25c5ae7ab5001"
          maxSize: 100GiB
    userVolumes:
      - name: openebs-data
        provisioning:
          diskSelector:
            match: disk.wwid == "eui.0000000001000000e4d25c5ae7ab5001"
          maxSize: 50GiB
        filesystem:
          type: xfs
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "8c:04:ba:9d:41:19"
        dhcp: false
        addresses:
          - "192.168.0.10/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        vip:
          ip: "192.168.0.11"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-logging.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/global/longhorn-partition.yaml"
    - "@./patches/global/machine-hugepages.yaml"
