machine:
  logging:
    destinations:
      - endpoint: "udp://192.168.0.11:5171"
        format: "json_lines"
#        extraTags:
#          node: "{{ .MachineConfig.MachineNetwork }}"
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: udp://192.168.0.11:5170

